spring:
  cloud:
    deployer:
      cloudfoundry:
        username: <your username>
        password: <your password>
        organization: <your CF org>
        space: <your CF space>
        apiEndpoint: <your API endpoint>
        domain: <default domain of your CF org>
        skipSslValidation: true