-- db/migration/V1__Create_products.sql
CREATE TABLE products (
        ID BIGINT AUTO_INCREMENT PRIMARY KEY,
        EAN VARCHAR(13) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NOT NULL,
        PRICE DOUBLE(10,2) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;